### ISSUE TITLE
Checkmarx api token endpoint not working

### ISSUE THREAD

**Issue by raysaik** [portilha/Checkmarx.API#10]
I am trying to integrate CxSAST scans inside my build pipeline. I use CAKE addins to call the Checkmarx rest api. But when i call the  checkmarx token endpoint  i am receiving the below exception- 

```
Http request exception while creating version... Exception Message: An error occurred while sending the request., Response body: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()

   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

   --- End of inner exception stack trace ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Cake.Http.CakeHttpClientHandler.<SendAsync>d__3.MoveNext() in C:\projects\cake-http\src\Cake.Http\CakeHttpClientHandler.cs:line 67

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
```

I am using the below method to make the POST request. Also it is working fine when i am doing it via postman.
'''
public string GetAccessToken(string CXUrl, string username, string pwd){
        CakeContext.Information("GetAccessToken before call");
        var getAccessTokenSettings = new HttpSettings
        {
            Headers = new Dictionary<string, string>
            {
              { "Content-Type", "application/x-www-form-urlencoded" },
              { "Accept-Encoding", "gzip, deflate, br" },
              { "Connection", "keep-alive" }
            },
            RequestBody = Encoding.ASCII.GetBytes(JsonConvert.SerializeObject(new
			{
				grant_type = "password",
                scope = "access_control_api sast_api",
                username = username,
                password = pwd,
                client_id = "resource_owner_sast_client",
                client_secret = "014DF517-39D1-4453-B7B3-9930C563627C"
			}))
            
        };
        var accessTokenUrl = CXUrl + "/auth/identity/connect/token";
        CakeContext.Information("The access token Url is " +accessTokenUrl);
        //var body = "{ \"grant_type\" : \"password\", \"scope\" : \"access_control_api sast_api\", \"username\" : \"" + username + "\", \"password\" : \"" + pwd + "\", \"client_id\" : \"resource_owner_sast_client\", \"client_secret\" : \"014DF517-39D1-4453-B7B3-9930C563627C\"}";

        //getAccessTokenSettings.SetRequestBody(body);

        //CakeContext.Information("Creating version request body: {0}", body);

        CakeContext.Information("Default Settings: {0}", getAccessTokenSettings.ToString());

        
        try
        {
            var response = CakeContext.HttpPost(accessTokenUrl, getAccessTokenSettings);
            CakeContext.Information("Version created. Response body: {0}", response);
        }

```

**Comment by portilha** [comment]
Hi Saikat Ray, thank you for reaching out, 

Are you using the Checkmarx.API calls or are you implementing your http calls? Did you found something that you need  missing in the API?, regarding your error, 

"System.Net.Http.WinHttpException: A security error occurred" -> https://stackoverflow.com/questions/49351595/net-core-httpclient-a-security-error-occurred-httprequestexception, it seems that there may be an insecure http connection being made here, 

This doesn't seem to be an issue regarding the Checkmarx.API but standard http connections issues.

Hope it helps,

**Comment by raysaik** [comment]
Thanks Pedro for looking into this.

I am calling the Checkmarx api code via the Cake.Http addin. I have found there is a "cake" specific tab in the Nuget page. Please can you tell me where i can get kore information on this or how to make calls to the checkmarx api using the checkmarx cake addin instead of the cake.http addin
![image](https://user-images.githubusercontent.com/24606602/147907304-c2e673be-475c-4d68-95de-a91a977c59eb.png)

**Comment by raysaik** [comment]
I will mark this as closed as I have been able to get around this using .net HttpClient but unfortunately could not implement using Checkmarx cake addin.
